 //import { Inter } from 'next/font/google'
import Layout from '@/components/layout/Layout'
import './globals.css'

//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'crypto markets',
  description: 'Generated by create next app',
  icons:{icons:"./favicon.ico"}
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
